/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.kapapa.kapapa.view;

import edu.kapapa.kapapa.entity.Memo;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;


/**
 *
 * @author ASUS
 */
public final class NotifFrame extends javax.swing.JFrame {
	Date dateTugas;
	int hariSekarang, bulanSekarang, tahunSekarang;
	String abcd;
	private List<Memo> list = new ArrayList<Memo>();

	
	/**
	 * Creates new form NotifFrame
	 */
	public NotifFrame() {
		initComponents();
		currentTime();
		lblTanggal.setText(checkTerdekat());
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                lblDeadline = new javax.swing.JLabel();
                lblTanggal = new javax.swing.JLabel();

                jPanel1.setBackground(new java.awt.Color(255, 255, 255));

                lblDeadline.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                lblDeadline.setText("Tugas dengan deadline terdekat:   ");

                lblTanggal.setText("jLabel1");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblDeadline)
                                .addGap(75, 75, 75)
                                .addComponent(lblTanggal)
                                .addContainerGap(336, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDeadline)
                                        .addComponent(lblTanggal))
                                .addContainerGap(157, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents
	public void setAbcd(String abcd) {
		this.abcd = abcd;
	}
	
	public void setList(List<Memo> list) {
		this.list = list;
	}
	
	public String checkTerdekat() {
		int terdekat = 1000;
		int index = 0;
		int totalHariSekarang = buatHari(bulanSekarang, hariSekarang, false);
		for (int i = 0; i < list.size(); i++) {
			
			Calendar cal = Calendar.getInstance();
			cal.setTime(list.get(i).getTanggal());
			boolean tahunDepan = true;
			if (tahunSekarang < (cal.get(Calendar.YEAR)))
				tahunDepan = false;
			int totalHariTugas = buatHari(cal.get(Calendar.MONTH), cal.get(Calendar.DAY_OF_MONTH), tahunDepan);
			if ((totalHariTugas - totalHariSekarang)< terdekat) {
				index = i;
			}
			
		}
		//Calendar cal = Calendar.getInstance();
		//cal.setTime(list.get(index).getTanggal());
		//return (String.valueOf(cal.get(Calendar.DAY_OF_MONTH)) + (String.valueOf(cal.get(Calendar.MONTH)) + (String.valueOf(cal.get(Calendar.YEAR)))));
		//return String.valueOf(list.size());
		return abcd;
	}
	
	
	public int buatHari (int bulan, int harii, boolean tahun) {
		
		int hari = 0;
		for (int i = 0; i<bulan-1; i++) {
			switch(i) {
				case 0:
					hari += 31;
					break;
				case 1: 
					hari += 28;
					break;
				case 2:
					hari += 31;
					break;
				case 3:
					hari += 30;
					break;
				case 4:
					hari += 31;
					break;
				case 5: 
					hari += 30;
					break;
				case 6:
					hari += 31;
					break;
				case 7:
					hari += 31;
					break;
				case 8:
					hari += 30;
					break;
				case 9: 
					hari += 31;
					break;
				case 10:
					hari += 30;
					break;
				case 11:
					hari += 31;
					break;
				default:
					hari += 0;
					
			}
		}
		if (tahun)
			hari += 365;
		return hari + harii;
		
		
	}
	
	public void currentTime () {
		 LocalDate localDate = LocalDate.now();
		 tahunSekarang = localDate.getYear();
		 bulanSekarang = localDate.getMonthValue();
		 hariSekarang = localDate.getDayOfMonth();
	}
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NotifFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NotifFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NotifFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NotifFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new NotifFrame().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lblDeadline;
        private javax.swing.JLabel lblTanggal;
        // End of variables declaration//GEN-END:variables
}
